export const GET_USERS = 'GET_USERS';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const SET_AUTH_USER = 'SET_AUTH_USER';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const ADD_QUESTION = 'ADD_QUESTION';
export const SAVE_NEW_QUESTION = 'SAVE_NEW_QUESTION';
export const ADD_QUESTION_TO_USER = 'ADD_QUESTION_TO_USER';