export const GET_USERS = 'GET_USERS';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const SET_AUTH_USER = 'SET_AUTH_USER';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const CURRENT_QUESTION = 'CURRENT_QUESTION'; 
export const GET_ANSWERED_QUESTIONS = 'GET_ANSWERED_QUESTIONS';
export const GET_UNANSWERED_QUESTIONS = 'GET_UNANSWERED_QUESTIONS';